src/UI/PortalConhecimento.UI.Web/Controllers/AnunciosController.cs
using PortalConhecimento.Domain.Interfaces.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Identity;
using System.Web;
using System.Web.Mvc;

namespace PortalConhecimento.UI.Web.Controllers
{
    [Authorize]
    public class AnunciosController : Controller
    {
        private IAnuncioRepository _anuncioRepository;
        public AnunciosController(IAnuncioRepository anuncioRepository)
        {
            _anuncioRepository = anuncioRepository;
        }

        public ActionResult Index()
        {
            var idUsuario = User.Identity.GetUserId<int>();
            var anuncios = _anuncioRepository.ListarPorUsuario(idUsuario);
            return View(anuncios);
        }

        public ActionResult Create()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _anuncioRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/UI/PortalConhecimento.UI.Web/Controllers/FAQController.cs
using PortalConhecimento.UI.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalConhecimento.UI.Web.Controllers
{
    public class FAQController : Controller
    {
        // GET: FAQ
        public ActionResult Index()
        {
            var model = FAQViewModel.ListarAtivos();
            return View(model);
        }
    }
}

src/UI/PortalConhecimento.UI.Web/Controllers/FaleConoscoController.cs
using AutoMapper;
using PortalConhecimento.Domain.Entities;
using PortalConhecimento.Domain.Interfaces.Repositories;
using PortalConhecimento.UI.Web.ViewModels;
using Recaptcha.Web;
using Recaptcha.Web.Mvc;
using System.Web.Mvc;

namespace PortalConhecimento.UI.Web.Controllers
{
    public class FaleConoscoController : Controller
    {
        private IContatoRepository _contatoRepository;
        public FaleConoscoController(IContatoRepository contatoRepository)
        {
            _contatoRepository = contatoRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ContatoViewModel model)
        {
            var recaptchaHelper = this.GetRecaptchaVerificationHelper();
            if (string.IsNullOrEmpty(recaptchaHelper.Response))
            {
                ModelState.AddModelError("", "O captcha é obrigatório.");
                return View(model);
            }

            var recaptchaResult = recaptchaHelper.VerifyRecaptchaResponse();
            if (recaptchaResult != RecaptchaVerificationResult.Success)
            {
                ModelState.AddModelError("", "Captcha incorreto.");
                return View(model);
            }

            if (ModelState.IsValid)
            {
                var entity = Mapper.Map<Contato>(model);
                _contatoRepository.Add(entity);
                TempData.Add("Message", "Seu contato foi recebido com sucesso! Em breve estaremos respondendo a sua dúvida!");
                return RedirectToAction("Index", "Home", null);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _contatoRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/UI/PortalConhecimento.UI.Web/Controllers/PalestrasCorporativasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalConhecimento.UI.Web.Controllers
{
    public class PalestrasCorporativasController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cadastro()
        {
            return View();
        }
    }
}

src/UI/PortalConhecimento.UI.Web/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/toastr")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container">
        <div class="row header">
            <div class="col-xs-6 marca"></div>
        </div>
        <div class="row bottom-space">
            <ul id="menu" class="anonymous-menu center-block">
                <li><a href="#" class="corporate"></a></li>
                <li><a href="#" class="aulas"></a></li>
                <li><a href="@Url.Action("Index", "FAQ")" class="duvidas"></a></li>
                <li><a href="@Url.Action("Index", "FaleConosco")" class="fale-conosco"></a></li>
            </ul>
        </div>
        <div class="row top-banner"></div>
        @RenderBody()
        <div class="row rodape">
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/toastr")
    @RenderSection("Scripts", false)
</body>
</html>

src/UI/PortalConhecimento.UI.Web/Views/Shared/_AnonymousHeaderPartial.cshtml
@model PortalConhecimento.UI.Web.ViewModels.LoginViewModel

<div class="row header">
    <div class="col-xs-6 marca"></div>
    <div class="col-xs-6">@Html.Partial("_LoginPartial", Model)</div>
</div>
<div class="row bottom-space">
    <ul id="menu" class="anonymous-menu center-block">
        <li><a href="@Url.Action("Index", "PalestrasCorporativas")" class="corporate"></a></li>
        <li><a href="@Url.Action("Index", "Aulas")" class="aulas"></a></li>
        <li><a href="@Url.Action("Index", "FAQ")" class="duvidas"></a></li>
        <li><a href="@Url.Action("Index", "FaleConosco")" class="fale-conosco"></a></li>
    </ul>
</div>

src/UI/PortalConhecimento.UI.Web/Views/Shared/_LoggedHeaderPartial.cshtml
<div class="row header">
    <div class="col-xs-6 marca"></div>
    <div class="col-xs-6 text-right">Seja bem vindo, @Context.User.Identity.Name!</div>
</div>
<div class="row bottom-space">
    <ul id="menu">
        <li><a href="@Url.Action("Index", "PalestrasCorporativas")" class="corporate"></a></li>
        <li><a href="@Url.Action("Index", "Aulas")" class="aulas"></a></li>
        <li><a href="@Url.Action("Index", "Anuncios")" class="registros"></a></li>
        <li><a href="@Url.Action("Index", "FAQ")" class="duvidas"></a></li>
        <li><a href="@Url.Action("Index", "FaleConosco")" class="fale-conosco"></a></li>
    </ul>
</div>

src/UI/PortalConhecimento.UI.Web/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/toastr")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Styles", false)
</head>
<body>
    <div class="container">
        @if (Context.User.Identity.IsAuthenticated)
        {
            @Html.Partial("_LoggedHeaderPartial")
        }
        else
        {
            @Html.Partial("_AnonymousHeaderPartial", new PortalConhecimento.UI.Web.ViewModels.LoginViewModel())
        }
        @RenderBody()
        <div class="row rodape">
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/toastr")
    @RenderSection("Scripts", false)
</body>
</html>